services:
  # Application PHP/Symfony
  app:
    build:
      context: ./docker/php
    volumes:
      - ./:/var/www/symfony
    depends_on:
      - rabbitmq
      - mongodb
    environment:
      - APP_ENV=dev
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - MONGODB_URL=mongodb://mongodb:27017
    networks:
      - app-network
  # Service RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"   # AMQP protocol port
      - "15672:15672" # Management UI
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - app-network

  # Service MongoDB
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  # Serveur web Nginx
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/symfony
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network

  # Worker Symfony pour le traitement asynchrone
  worker:
    build:
      context: ./docker/php
    volumes:
      - ./:/var/www/symfony
    depends_on:
      - rabbitmq
      - mongodb
    command: php bin/console messenger:consume async --time-limit=3600
    environment:
      - APP_ENV=dev
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - MONGODB_URL=mongodb://mongodb:27017
    networks:
      - app-network

networks:
  app-network:

volumes:
  rabbitmq_data:
  mongodb_data: