version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8000:80"  # Changed to port 8000 to match your curl command
    volumes:
      - ./:/var/www/symfony
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - app-network

  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./:/var/www/symfony
    depends_on:
      - mongodb
      - rabbitmq
    networks:
      - app-network

  worker:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./:/var/www/symfony
    depends_on:
      - php
      - rabbitmq
      - mongodb
    command: ["php", "skeleton/bin/console", "messenger:consume", "async_email", "--limit=10", "-vv"]
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"  # Management interface
      - "5672:5672"    # AMQP port
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"  # MongoDB port
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=email_api
    networks:
      - app-network
      
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH=false
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_URL=mongodb://mongodb:27017
    depends_on:
      - mongodb
    networks:
      - app-network

  mailpit:
    image: axllent/mailpit
    restart: always
    ports:
      - "1025:1025"  # SMTP port
      - "8025:8025"  # Web UI port
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  rabbitmq_data:
  mongodb_data:
