services:
  # Default configuration for services
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  # Makes classes in src/ available to be used as services
  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'

  # Add this configuration for EmailService
  App\Service\EmailService:
    arguments:
      $projectDir: '%kernel.project_dir%'